// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzO9k_8PsRbh2O0FmbtvgTgAX36XievpY',
    appId: '1:150169921226:web:9c66f1e9efdcb19b4e3633',
    messagingSenderId: '150169921226',
    projectId: 'adapt-81b7f',
    authDomain: 'adapt-81b7f.firebaseapp.com',
    storageBucket: 'adapt-81b7f.firebasestorage.app',
    measurementId: 'G-TZ0HP8JWW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8VZtuSPMVQsvH55F6SwacDC_tB1K_Dw',
    appId: '1:150169921226:android:b0d8b25c79dbe91c4e3633',
    messagingSenderId: '150169921226',
    projectId: 'adapt-81b7f',
    storageBucket: 'adapt-81b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT2UThD8J80PtYB1VWYMtlgaBU7p7WMvs',
    appId: '1:150169921226:ios:3a76e5258e24c1ef4e3633',
    messagingSenderId: '150169921226',
    projectId: 'adapt-81b7f',
    storageBucket: 'adapt-81b7f.firebasestorage.app',
    iosBundleId: 'com.example.widgetTest',
  );

}